version: 2

models:
  - name : stg_info_victime
    columns : 
      - name : victime_id
        constraints:
          - type : primary_key
      - name : gravite_accident
      - name : sexe
      - name : trajet_victime
      - name : equipement_securite
      - name : num_acc
      - name : created_at
      - name : updated_at
  - name :  stg_inf_accident
  - name : stg_info_vehicule
    columns:
      - name : info_vehi_id
        constraints : 
          - type : primary_key
      - name: manoeuvre_vehicule_avant
      - name : vehiculeid
      - name : typevehicules
      - name : info_commune
      - name : created_at
      - name : updated_at
  - name : stg_loc_accident
    columns :
      - name : num_acc
        constraints:
          - type : primary_key
        tests:
          - not_null
      - name : departement
      - name : comune 
      - name : lat
      - name : long