name : run dbt with SSH

on:
  push:
    branches : ["main","recette"]
  workflow_dispatch:

jobs:
  test_dbt:
    name: Tester les modèles dbt et scripts python
    runs-on: ubuntu-latest
    environment: env_var

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASS }}
          POSTGRES_DB: ${{ secrets.DB_BDD }}
        options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
        ports : 
            - 5432:5432
    steps:
      - name: récupérer le code
        uses: actions/checkout@v5

      - name: installer python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      
      - name: installer dbt
        run: |
          pip install dbt-core dbt-postgres
          dbt --version
      - name: Installer les dependances dbt
        run: |
          if [ -f packages.yml ]; then
            dbt deps 
          fi
      
      - name: Debug - verfier les fichiers 
        run :  |
          ls -la
          echo "Vérifications des profiles.yml"
          cat profiles.yml 2>/dev/null || echo "profiles.yml non trouvé"
      
      - name: Install ALL dependencies
        run: |
          pip install --upgrade pip
          
          # Toutes les dépendances en une seule ligne
          pip install \
            pandas \
            numpy \
            sqlalchemy \
            psycopg2-binary \
            requests \
            python-dotenv \
            python-dateutil \
            pytz \
            dbt-core \
            dbt-postgres
          
            # Afficher les versions installées
            echo "=== VERSIONS INSTALLÉES ==="
            pip list
          
            # Vérifier les imports
            echo "=== VÉRIFICATION DES IMPORTS ==="
            python -c "import pandas; print('✅ pandas', pandas.__version__)"
            python -c "import numpy; print('✅ numpy', numpy.__version__)"
            python -c "import sqlalchemy; print('✅ sqlalchemy', sqlalchemy.__version__)"
            python -c "import psycopg2; print('✅ psycopg2', psycopg2.__version__)"
            python -c "import requests; print('✅ requests', requests.__version__)"
            python -c "from dotenv import load_dotenv; print('✅ python-dotenv')"
          

      - name: Vérifier les secrets
        run: |
          if [ -z "${{ secrets.DB_PASS }}" ]; then
            echo " DB_PASS est vide"
            exit 1
          else
            echo " DB_PASS est présent"
          fi

      - name: Créer le schéma
        run: |
          PGPASSWORD=${{ secrets.DB_PASS }} psql \
          -h localhost \
          -U ${{ secrets.DB_USER }} \
          -d ${{ secrets.DB_BDD }} \
          -c "CREATE SCHEMA IF NOT EXISTS ${{ secrets.DB_SCHEMA }};"

            echo "Schémas présents :"

          PGPASSWORD=${{ secrets.DB_PASS }} psql \
          -h localhost \
          -U ${{ secrets.DB_USER }} \
          -d ${{ secrets.DB_BDD }} \
          -c "\dn"

      - name: requeter API Departements et communes
        run: python ingestion/main.py
        env:
          DB_BDD: ${{ secrets.DB_BDD }} 
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_SCHEMA: ${{ secrets.DB_SCHEMA }}
      
      - name: compiler les modèles
        run:  dbt compile
        env:
          DB_BDD: ${{ secrets.DB_BDD }}         
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_SCHEMA: ${{ secrets.DB_SCHEMA }} 

      - name: exécuter les modèles
        run:  dbt run
        env:
          DB_BDD: ${{ secrets.DB_BDD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_SCHEMA : ${{ secrets.DB_SCHEMA }}
      
      - name: testter les modèles
        run: dbt test
        env:
          DB_BDD: ${{ secrets.DB_BDD }} 
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_SCHEMA : ${{ secrets.DB_SCHEMA }}
      
      - name: Afficher les tables créées (debug)
        run: |
          PGPASSWORD=${{ secrets.DB_PASS }} psql -h localhost -U ${{ secrets.DB_USER }} -d ${{ secrets.DB_BDD }}  -c "\dt dbt_test_ci.*"
        env:
          PGPASSWORD: ${{ secrets.DB_PASS }}

  generate_docs:
    name: Générer la documentation
    runs-on: ubuntu-latest
    needs: test_dbt
    environment: env_var
    if: github.ref == 'refs/heads/main'

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASS }}
          POSTGRES_DB: ${{ secrets.DB_BDD }}
        options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
        ports : 
            - 5432:5432

    steps:
      - name: récupérer le code
        uses: actions/checkout@v5

      - name: Installer python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      
      - name: installer dbt
        run: |
          pip install dbt-core dbt-postgres
          dbt --version
      
      - name: Installer les dependances dbt
        run: |
          if [ -f packages.yml ]; then
            dbt deps 
          fi

      - name: Générer la documentation
        run : dbt docs generate
        env:
          DB_BDD: ${{ secrets.DB_BDD }} 
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_SCHEMA : ${{ secrets.DB_SCHEMA }}
      
      - name: Uploader la documentation
        uses: actions/upload-artifact@v5
        with:
          name: dbt-docs
          path: target/      